# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from delivery.rpc import inventory_pb2 as delivery_dot_rpc_dot_inventory__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in delivery/rpc/inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reserve = channel.unary_unary(
                '/delivery.inventory.Inventory/Reserve',
                request_serializer=delivery_dot_rpc_dot_inventory__pb2.ReserveRequest.SerializeToString,
                response_deserializer=delivery_dot_rpc_dot_inventory__pb2.ReserveReply.FromString,
                _registered_method=True)
        self.Stock = channel.unary_unary(
                '/delivery.inventory.Inventory/Stock',
                request_serializer=delivery_dot_rpc_dot_inventory__pb2.StockRequest.SerializeToString,
                response_deserializer=delivery_dot_rpc_dot_inventory__pb2.StockReply.FromString,
                _registered_method=True)


class InventoryServicer:
    """Missing associated documentation comment in .proto file."""

    def Reserve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reserve': grpc.unary_unary_rpc_method_handler(
                    servicer.Reserve,
                    request_deserializer=delivery_dot_rpc_dot_inventory__pb2.ReserveRequest.FromString,
                    response_serializer=delivery_dot_rpc_dot_inventory__pb2.ReserveReply.SerializeToString,
            ),
            'Stock': grpc.unary_unary_rpc_method_handler(
                    servicer.Stock,
                    request_deserializer=delivery_dot_rpc_dot_inventory__pb2.StockRequest.FromString,
                    response_serializer=delivery_dot_rpc_dot_inventory__pb2.StockReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'delivery.inventory.Inventory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('delivery.inventory.Inventory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inventory:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/delivery.inventory.Inventory/Reserve',
            delivery_dot_rpc_dot_inventory__pb2.ReserveRequest.SerializeToString,
            delivery_dot_rpc_dot_inventory__pb2.ReserveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/delivery.inventory.Inventory/Stock',
            delivery_dot_rpc_dot_inventory__pb2.StockRequest.SerializeToString,
            delivery_dot_rpc_dot_inventory__pb2.StockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
