# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery/rpc/inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'delivery/rpc/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x64\x65livery/rpc/inventory.proto\x12\x12\x64\x65livery.inventory\"A\n\x0eReserveRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0b\n\x03sku\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"\x1f\n\x0cReserveReply\x12\x0f\n\x07outcome\x18\x01 \x01(\t\"\x1b\n\x0cStockRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\",\n\nStockReply\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x11\n\tavailable\x18\x02 \x01(\x05\x32\xa7\x01\n\tInventory\x12O\n\x07Reserve\x12\".delivery.inventory.ReserveRequest\x1a .delivery.inventory.ReserveReply\x12I\n\x05Stock\x12 .delivery.inventory.StockRequest\x1a\x1e.delivery.inventory.StockReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery.rpc.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESERVEREQUEST']._serialized_start=52
  _globals['_RESERVEREQUEST']._serialized_end=117
  _globals['_RESERVEREPLY']._serialized_start=119
  _globals['_RESERVEREPLY']._serialized_end=150
  _globals['_STOCKREQUEST']._serialized_start=152
  _globals['_STOCKREQUEST']._serialized_end=179
  _globals['_STOCKREPLY']._serialized_start=181
  _globals['_STOCKREPLY']._serialized_end=225
  _globals['_INVENTORY']._serialized_start=228
  _globals['_INVENTORY']._serialized_end=395
# @@protoc_insertion_point(module_scope)
